# low_voltage
FROM --platform=linux/arm64 centos:centos7

ENV WDIR=/usr/app
WORKDIR $WDIR

RUN yum update -y && \
yum provides applydeltarpm && \
touch /tmp/smap_install_ni_anyway && \
yum install -y \
          python3 \
          rpm \
          deltarpm \
          unzip \
          libusb \
          libivivisa0 \
          ni-icp.noarch \
          ni-visa \
          ni-daqmx \
          kernel-devel && \
    yum clean all && rm -rf /var/cache/yum && \
    python3 -m pip install --upgrade && \
    python3 -m pip install -U PyVISA-py PyVISA



