version: "3"
services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    restart: always
    ports:
      - "1883:1883"
    expose:
      - "1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./mosquitto/config:/mosquitto/config
    
  lv_hmp4040:
    image: centos:low_voltage
    build: /usr/app/low_voltage
    restart: always
    stdin_open: true
    tty: true 
    volumes:
      - low_voltage:/usr/app/low_voltage/

volumes:
  mosquitto_data:
  mosquitto_log:
  low_voltage:
